### ISSUE TITLE
Uitleg voor collega's maken

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/raamwerk-geostandaarden-oud#3]
Ik ben klaar om de raamwerk concepttekst te delen met collega's zodat ze het kunnen gaan reviewen. 1) Er is nog een stukje documentatie nodig om ze op weg te helpen met GitHub. Hoe maak ik een account aan, wat zijn de basics. 

2) En meer concreet, hoe kunnen ze bijdragen aan het raamwerk-geostandaarden project. Ik heb dit in [CONTRIBUTING.md](CONTRIBUTING.md) proberen te omschrijven maar dit kan denk ik beter.

**Comment by ndkv** [comment]
Mooi werk!

Ik ben bijna klaar met de github documentatie. Ik push het naar geonovum-labs/handleidingen/starten-met-github.md

**Comment by ndkv** [comment]
Klaar! 

Handleiding staat [hier](https://github.com/Geonovum/geonovum/blob/master/handleidingen/starten-met-github.md).
